"""initial schema with users and sms tables

Revision ID: b15c4b8243d8
Revises: 
Create Date: 2025-12-22 10:03:39.667422

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b15c4b8243d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('api_key', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_index('idx_users_api_key', 'users', ['api_key'], unique=False)
    op.create_table('sms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=70), nullable=False),
    sa.Column('sms_type', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'created_at'),
    postgresql_partition_by='RANGE (created_at)'
    )

    op.execute("""
        CREATE TABLE sms_2025_01 PARTITION OF sms
        FOR VALUES FROM ('2025-01-01') TO ('2025-02-01')
    """)

    op.execute("""
        CREATE TABLE sms_2025_02 PARTITION OF sms
        FOR VALUES FROM ('2025-02-01') TO ('2025-03-01')
    """)

    op.execute("""
        CREATE TABLE sms_2025_03 PARTITION OF sms
        FOR VALUES FROM ('2025-03-01') TO ('2025-04-01')
    """)
    op.create_index('idx_sms_created', 'sms', ['created_at'], unique=False)
    op.create_index('idx_sms_status', 'sms', ['status'], unique=False)
    op.create_index('idx_sms_user_created', 'sms', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_sms_user_status', 'sms', ['user_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sms_user_status', table_name='sms')
    op.drop_index('idx_sms_user_created', table_name='sms')
    op.drop_index('idx_sms_status', table_name='sms')
    op.drop_index('idx_sms_created', table_name='sms')
    op.drop_table('sms')
    op.drop_index('idx_users_api_key', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
